name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant permission
        run: chmod +x ./gradlew

      - name: Run tests and generate coverage reports
        run: ./gradlew :jhu-seclab-cobra-framework:test :jhu-seclab-cobra-framework:koverXmlReport

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: jhu-seclab-cobra/framework
          files: ./framework/build/reports/kover/report.xml
